//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.25 at 06:06:29 PM PDT 
//


package in.gov.incometaxindiaefiling.y2011_2012.corp;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TaxAtNormalRates">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TaxAtSpecialRates">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TaxPayableOnTotInc">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "taxAtNormalRates",
    "taxAtSpecialRates",
    "taxPayableOnTotInc"
})
@XmlRootElement(name = "TaxPayableOnTI")
public class TaxPayableOnTI {

    @XmlElement(name = "TaxAtNormalRates", required = true, defaultValue = "0")
    protected BigInteger taxAtNormalRates;
    @XmlElement(name = "TaxAtSpecialRates", required = true, defaultValue = "0")
    protected BigInteger taxAtSpecialRates;
    @XmlElement(name = "TaxPayableOnTotInc", required = true, defaultValue = "0")
    protected BigInteger taxPayableOnTotInc;

    /**
     * Gets the value of the taxAtNormalRates property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTaxAtNormalRates() {
        return taxAtNormalRates;
    }

    /**
     * Sets the value of the taxAtNormalRates property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTaxAtNormalRates(BigInteger value) {
        this.taxAtNormalRates = value;
    }

    /**
     * Gets the value of the taxAtSpecialRates property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTaxAtSpecialRates() {
        return taxAtSpecialRates;
    }

    /**
     * Sets the value of the taxAtSpecialRates property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTaxAtSpecialRates(BigInteger value) {
        this.taxAtSpecialRates = value;
    }

    /**
     * Gets the value of the taxPayableOnTotInc property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTaxPayableOnTotInc() {
        return taxPayableOnTotInc;
    }

    /**
     * Sets the value of the taxPayableOnTotInc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTaxPayableOnTotInc(BigInteger value) {
        this.taxPayableOnTotInc = value;
    }

}
