//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.04 at 11:43:52 AM PDT 
//


package in.gov.incometaxindiaefiling.y2012_2013.itr6;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.CorpScheduleBP;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.CreationInfo;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.FormITR6;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ITRScheduleFSI;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ITRScheduleUD;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.PARTABSFor6;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.PARTAOI;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.PARTAPLFor6;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.PARTAQD;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.PartAGEN1;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.PartAGEN2For6;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.PartBTI;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.PartBTTI;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.Schedule10A;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.Schedule10AA;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.Schedule10B;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.Schedule10BA;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.Schedule80G;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.Schedule80IA;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.Schedule80IB;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.Schedule80IC;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ScheduleBA;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ScheduleBFLA;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ScheduleCFL;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ScheduleCG;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ScheduleCYLA;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ScheduleDCG;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ScheduleDDT;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ScheduleDDTP;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ScheduleDEP;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ScheduleDOA;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ScheduleDPM;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ScheduleEI;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ScheduleESR;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ScheduleFA;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ScheduleFSI;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ScheduleHP;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ScheduleIT;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ScheduleMAT;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ScheduleMATC;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ScheduleOS;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ScheduleSI;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ScheduleSTTC;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ScheduleTCS;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ScheduleTDS2;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ScheduleTR1;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.ScheduleVIA;
import in.gov.incometaxindiaefiling.y2012_2013.corpmaster.Verification;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}CreationInfo"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}Form_ITR6"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}PartA_GEN1"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}PartA_GEN2For6"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}PARTA_BSFor6"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}PARTA_PLFor6"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}PARTA_OI" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}PARTA_QD" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}PartB-TI"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}PartB_TTI"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}Verification"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ScheduleBA" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ScheduleHP" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}CorpScheduleBP"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ScheduleDPM" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ScheduleDOA" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ScheduleDEP" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ScheduleDCG" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ScheduleESR" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ScheduleCG" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ScheduleOS" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ScheduleCYLA" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ScheduleBFLA" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ScheduleCFL" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}Schedule10A" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}Schedule10AA" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}Schedule10B" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}Schedule10BA" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}Schedule80G" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}Schedule80_IA" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}Schedule80_IB" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}Schedule80_IC" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ScheduleVIA" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ScheduleSTTC" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ScheduleSI" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ScheduleEI" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ScheduleMAT"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ScheduleMATC"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ScheduleDDT" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ScheduleIT" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ScheduleTDS2" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ScheduleTCS" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ScheduleDDTP" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ITRScheduleUD" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ScheduleTR1" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ScheduleFA" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ITRScheduleFSI" minOccurs="0"/>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/Corpmaster}ScheduleFSI" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "creationInfo",
    "formITR6",
    "partAGEN1",
    "partAGEN2For6",
    "partabsFor6",
    "partaplFor6",
    "partaoi",
    "partaqd",
    "partBTI",
    "partBTTI",
    "verification",
    "scheduleBA",
    "scheduleHP",
    "corpScheduleBP",
    "scheduleDPM",
    "scheduleDOA",
    "scheduleDEP",
    "scheduleDCG",
    "scheduleESR",
    "scheduleCG",
    "scheduleOS",
    "scheduleCYLA",
    "scheduleBFLA",
    "scheduleCFL",
    "schedule10A",
    "schedule10AA",
    "schedule10B",
    "schedule10BA",
    "schedule80G",
    "schedule80IA",
    "schedule80IB",
    "schedule80IC",
    "scheduleVIA",
    "scheduleSTTC",
    "scheduleSI",
    "scheduleEI",
    "scheduleMAT",
    "scheduleMATC",
    "scheduleDDT",
    "scheduleIT",
    "scheduleTDS2",
    "scheduleTCS",
    "scheduleDDTP",
    "itrScheduleUD",
    "scheduleTR1",
    "scheduleFA",
    "itrScheduleFSI",
    "scheduleFSI"
})
@XmlRootElement(name = "ITR6")
public class ITR6 {

    @XmlElement(name = "CreationInfo", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster", required = true)
    protected CreationInfo creationInfo;
    @XmlElement(name = "Form_ITR6", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster", required = true)
    protected FormITR6 formITR6;
    @XmlElement(name = "PartA_GEN1", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster", required = true)
    protected PartAGEN1 partAGEN1;
    @XmlElement(name = "PartA_GEN2For6", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster", required = true)
    protected PartAGEN2For6 partAGEN2For6;
    @XmlElement(name = "PARTA_BSFor6", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster", required = true)
    protected PARTABSFor6 partabsFor6;
    @XmlElement(name = "PARTA_PLFor6", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster", required = true)
    protected PARTAPLFor6 partaplFor6;
    @XmlElement(name = "PARTA_OI", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected PARTAOI partaoi;
    @XmlElement(name = "PARTA_QD", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected PARTAQD partaqd;
    @XmlElement(name = "PartB-TI", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster", required = true)
    protected PartBTI partBTI;
    @XmlElement(name = "PartB_TTI", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster", required = true)
    protected PartBTTI partBTTI;
    @XmlElement(name = "Verification", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster", required = true)
    protected Verification verification;
    @XmlElement(name = "ScheduleBA", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected ScheduleBA scheduleBA;
    @XmlElement(name = "ScheduleHP", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected ScheduleHP scheduleHP;
    @XmlElement(name = "CorpScheduleBP", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster", required = true)
    protected CorpScheduleBP corpScheduleBP;
    @XmlElement(name = "ScheduleDPM", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected ScheduleDPM scheduleDPM;
    @XmlElement(name = "ScheduleDOA", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected ScheduleDOA scheduleDOA;
    @XmlElement(name = "ScheduleDEP", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected ScheduleDEP scheduleDEP;
    @XmlElement(name = "ScheduleDCG", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected ScheduleDCG scheduleDCG;
    @XmlElement(name = "ScheduleESR", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected ScheduleESR scheduleESR;
    @XmlElement(name = "ScheduleCG", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected ScheduleCG scheduleCG;
    @XmlElement(name = "ScheduleOS", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected ScheduleOS scheduleOS;
    @XmlElement(name = "ScheduleCYLA", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected ScheduleCYLA scheduleCYLA;
    @XmlElement(name = "ScheduleBFLA", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected ScheduleBFLA scheduleBFLA;
    @XmlElement(name = "ScheduleCFL", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected ScheduleCFL scheduleCFL;
    @XmlElement(name = "Schedule10A", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected Schedule10A schedule10A;
    @XmlElement(name = "Schedule10AA", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected Schedule10AA schedule10AA;
    @XmlElement(name = "Schedule10B", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected Schedule10B schedule10B;
    @XmlElement(name = "Schedule10BA", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected Schedule10BA schedule10BA;
    @XmlElement(name = "Schedule80G", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected Schedule80G schedule80G;
    @XmlElement(name = "Schedule80_IA", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected Schedule80IA schedule80IA;
    @XmlElement(name = "Schedule80_IB", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected Schedule80IB schedule80IB;
    @XmlElement(name = "Schedule80_IC", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected Schedule80IC schedule80IC;
    @XmlElement(name = "ScheduleVIA", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected ScheduleVIA scheduleVIA;
    @XmlElement(name = "ScheduleSTTC", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected ScheduleSTTC scheduleSTTC;
    @XmlElement(name = "ScheduleSI", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected ScheduleSI scheduleSI;
    @XmlElement(name = "ScheduleEI", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected ScheduleEI scheduleEI;
    @XmlElement(name = "ScheduleMAT", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster", required = true)
    protected ScheduleMAT scheduleMAT;
    @XmlElement(name = "ScheduleMATC", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster", required = true)
    protected ScheduleMATC scheduleMATC;
    @XmlElement(name = "ScheduleDDT", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected ScheduleDDT scheduleDDT;
    @XmlElement(name = "ScheduleIT", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected ScheduleIT scheduleIT;
    @XmlElement(name = "ScheduleTDS2", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected ScheduleTDS2 scheduleTDS2;
    @XmlElement(name = "ScheduleTCS", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected ScheduleTCS scheduleTCS;
    @XmlElement(name = "ScheduleDDTP", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected ScheduleDDTP scheduleDDTP;
    @XmlElement(name = "ITRScheduleUD", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected ITRScheduleUD itrScheduleUD;
    @XmlElement(name = "ScheduleTR1", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected ScheduleTR1 scheduleTR1;
    @XmlElement(name = "ScheduleFA", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected ScheduleFA scheduleFA;
    @XmlElement(name = "ITRScheduleFSI", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected ITRScheduleFSI itrScheduleFSI;
    @XmlElement(name = "ScheduleFSI", namespace = "http://incometaxindiaefiling.gov.in/Corpmaster")
    protected ScheduleFSI scheduleFSI;

    /**
     * Gets the value of the creationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CreationInfo }
     *     
     */
    public CreationInfo getCreationInfo() {
        return creationInfo;
    }

    /**
     * Sets the value of the creationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreationInfo }
     *     
     */
    public void setCreationInfo(CreationInfo value) {
        this.creationInfo = value;
    }

    /**
     * Gets the value of the formITR6 property.
     * 
     * @return
     *     possible object is
     *     {@link FormITR6 }
     *     
     */
    public FormITR6 getFormITR6() {
        return formITR6;
    }

    /**
     * Sets the value of the formITR6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormITR6 }
     *     
     */
    public void setFormITR6(FormITR6 value) {
        this.formITR6 = value;
    }

    /**
     * Gets the value of the partAGEN1 property.
     * 
     * @return
     *     possible object is
     *     {@link PartAGEN1 }
     *     
     */
    public PartAGEN1 getPartAGEN1() {
        return partAGEN1;
    }

    /**
     * Sets the value of the partAGEN1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartAGEN1 }
     *     
     */
    public void setPartAGEN1(PartAGEN1 value) {
        this.partAGEN1 = value;
    }

    /**
     * Gets the value of the partAGEN2For6 property.
     * 
     * @return
     *     possible object is
     *     {@link PartAGEN2For6 }
     *     
     */
    public PartAGEN2For6 getPartAGEN2For6() {
        return partAGEN2For6;
    }

    /**
     * Sets the value of the partAGEN2For6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartAGEN2For6 }
     *     
     */
    public void setPartAGEN2For6(PartAGEN2For6 value) {
        this.partAGEN2For6 = value;
    }

    /**
     * Gets the value of the partabsFor6 property.
     * 
     * @return
     *     possible object is
     *     {@link PARTABSFor6 }
     *     
     */
    public PARTABSFor6 getPARTABSFor6() {
        return partabsFor6;
    }

    /**
     * Sets the value of the partabsFor6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PARTABSFor6 }
     *     
     */
    public void setPARTABSFor6(PARTABSFor6 value) {
        this.partabsFor6 = value;
    }

    /**
     * Gets the value of the partaplFor6 property.
     * 
     * @return
     *     possible object is
     *     {@link PARTAPLFor6 }
     *     
     */
    public PARTAPLFor6 getPARTAPLFor6() {
        return partaplFor6;
    }

    /**
     * Sets the value of the partaplFor6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PARTAPLFor6 }
     *     
     */
    public void setPARTAPLFor6(PARTAPLFor6 value) {
        this.partaplFor6 = value;
    }

    /**
     * Gets the value of the partaoi property.
     * 
     * @return
     *     possible object is
     *     {@link PARTAOI }
     *     
     */
    public PARTAOI getPARTAOI() {
        return partaoi;
    }

    /**
     * Sets the value of the partaoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link PARTAOI }
     *     
     */
    public void setPARTAOI(PARTAOI value) {
        this.partaoi = value;
    }

    /**
     * Gets the value of the partaqd property.
     * 
     * @return
     *     possible object is
     *     {@link PARTAQD }
     *     
     */
    public PARTAQD getPARTAQD() {
        return partaqd;
    }

    /**
     * Sets the value of the partaqd property.
     * 
     * @param value
     *     allowed object is
     *     {@link PARTAQD }
     *     
     */
    public void setPARTAQD(PARTAQD value) {
        this.partaqd = value;
    }

    /**
     * Gets the value of the partBTI property.
     * 
     * @return
     *     possible object is
     *     {@link PartBTI }
     *     
     */
    public PartBTI getPartBTI() {
        return partBTI;
    }

    /**
     * Sets the value of the partBTI property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartBTI }
     *     
     */
    public void setPartBTI(PartBTI value) {
        this.partBTI = value;
    }

    /**
     * Gets the value of the partBTTI property.
     * 
     * @return
     *     possible object is
     *     {@link PartBTTI }
     *     
     */
    public PartBTTI getPartBTTI() {
        return partBTTI;
    }

    /**
     * Sets the value of the partBTTI property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartBTTI }
     *     
     */
    public void setPartBTTI(PartBTTI value) {
        this.partBTTI = value;
    }

    /**
     * Gets the value of the verification property.
     * 
     * @return
     *     possible object is
     *     {@link Verification }
     *     
     */
    public Verification getVerification() {
        return verification;
    }

    /**
     * Sets the value of the verification property.
     * 
     * @param value
     *     allowed object is
     *     {@link Verification }
     *     
     */
    public void setVerification(Verification value) {
        this.verification = value;
    }

    /**
     * Gets the value of the scheduleBA property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleBA }
     *     
     */
    public ScheduleBA getScheduleBA() {
        return scheduleBA;
    }

    /**
     * Sets the value of the scheduleBA property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleBA }
     *     
     */
    public void setScheduleBA(ScheduleBA value) {
        this.scheduleBA = value;
    }

    /**
     * Gets the value of the scheduleHP property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleHP }
     *     
     */
    public ScheduleHP getScheduleHP() {
        return scheduleHP;
    }

    /**
     * Sets the value of the scheduleHP property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleHP }
     *     
     */
    public void setScheduleHP(ScheduleHP value) {
        this.scheduleHP = value;
    }

    /**
     * Gets the value of the corpScheduleBP property.
     * 
     * @return
     *     possible object is
     *     {@link CorpScheduleBP }
     *     
     */
    public CorpScheduleBP getCorpScheduleBP() {
        return corpScheduleBP;
    }

    /**
     * Sets the value of the corpScheduleBP property.
     * 
     * @param value
     *     allowed object is
     *     {@link CorpScheduleBP }
     *     
     */
    public void setCorpScheduleBP(CorpScheduleBP value) {
        this.corpScheduleBP = value;
    }

    /**
     * Gets the value of the scheduleDPM property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleDPM }
     *     
     */
    public ScheduleDPM getScheduleDPM() {
        return scheduleDPM;
    }

    /**
     * Sets the value of the scheduleDPM property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleDPM }
     *     
     */
    public void setScheduleDPM(ScheduleDPM value) {
        this.scheduleDPM = value;
    }

    /**
     * Gets the value of the scheduleDOA property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleDOA }
     *     
     */
    public ScheduleDOA getScheduleDOA() {
        return scheduleDOA;
    }

    /**
     * Sets the value of the scheduleDOA property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleDOA }
     *     
     */
    public void setScheduleDOA(ScheduleDOA value) {
        this.scheduleDOA = value;
    }

    /**
     * Gets the value of the scheduleDEP property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleDEP }
     *     
     */
    public ScheduleDEP getScheduleDEP() {
        return scheduleDEP;
    }

    /**
     * Sets the value of the scheduleDEP property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleDEP }
     *     
     */
    public void setScheduleDEP(ScheduleDEP value) {
        this.scheduleDEP = value;
    }

    /**
     * Gets the value of the scheduleDCG property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleDCG }
     *     
     */
    public ScheduleDCG getScheduleDCG() {
        return scheduleDCG;
    }

    /**
     * Sets the value of the scheduleDCG property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleDCG }
     *     
     */
    public void setScheduleDCG(ScheduleDCG value) {
        this.scheduleDCG = value;
    }

    /**
     * Gets the value of the scheduleESR property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleESR }
     *     
     */
    public ScheduleESR getScheduleESR() {
        return scheduleESR;
    }

    /**
     * Sets the value of the scheduleESR property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleESR }
     *     
     */
    public void setScheduleESR(ScheduleESR value) {
        this.scheduleESR = value;
    }

    /**
     * Gets the value of the scheduleCG property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleCG }
     *     
     */
    public ScheduleCG getScheduleCG() {
        return scheduleCG;
    }

    /**
     * Sets the value of the scheduleCG property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleCG }
     *     
     */
    public void setScheduleCG(ScheduleCG value) {
        this.scheduleCG = value;
    }

    /**
     * Gets the value of the scheduleOS property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleOS }
     *     
     */
    public ScheduleOS getScheduleOS() {
        return scheduleOS;
    }

    /**
     * Sets the value of the scheduleOS property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleOS }
     *     
     */
    public void setScheduleOS(ScheduleOS value) {
        this.scheduleOS = value;
    }

    /**
     * Gets the value of the scheduleCYLA property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleCYLA }
     *     
     */
    public ScheduleCYLA getScheduleCYLA() {
        return scheduleCYLA;
    }

    /**
     * Sets the value of the scheduleCYLA property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleCYLA }
     *     
     */
    public void setScheduleCYLA(ScheduleCYLA value) {
        this.scheduleCYLA = value;
    }

    /**
     * Gets the value of the scheduleBFLA property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleBFLA }
     *     
     */
    public ScheduleBFLA getScheduleBFLA() {
        return scheduleBFLA;
    }

    /**
     * Sets the value of the scheduleBFLA property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleBFLA }
     *     
     */
    public void setScheduleBFLA(ScheduleBFLA value) {
        this.scheduleBFLA = value;
    }

    /**
     * Gets the value of the scheduleCFL property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleCFL }
     *     
     */
    public ScheduleCFL getScheduleCFL() {
        return scheduleCFL;
    }

    /**
     * Sets the value of the scheduleCFL property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleCFL }
     *     
     */
    public void setScheduleCFL(ScheduleCFL value) {
        this.scheduleCFL = value;
    }

    /**
     * Gets the value of the schedule10A property.
     * 
     * @return
     *     possible object is
     *     {@link Schedule10A }
     *     
     */
    public Schedule10A getSchedule10A() {
        return schedule10A;
    }

    /**
     * Sets the value of the schedule10A property.
     * 
     * @param value
     *     allowed object is
     *     {@link Schedule10A }
     *     
     */
    public void setSchedule10A(Schedule10A value) {
        this.schedule10A = value;
    }

    /**
     * Gets the value of the schedule10AA property.
     * 
     * @return
     *     possible object is
     *     {@link Schedule10AA }
     *     
     */
    public Schedule10AA getSchedule10AA() {
        return schedule10AA;
    }

    /**
     * Sets the value of the schedule10AA property.
     * 
     * @param value
     *     allowed object is
     *     {@link Schedule10AA }
     *     
     */
    public void setSchedule10AA(Schedule10AA value) {
        this.schedule10AA = value;
    }

    /**
     * Gets the value of the schedule10B property.
     * 
     * @return
     *     possible object is
     *     {@link Schedule10B }
     *     
     */
    public Schedule10B getSchedule10B() {
        return schedule10B;
    }

    /**
     * Sets the value of the schedule10B property.
     * 
     * @param value
     *     allowed object is
     *     {@link Schedule10B }
     *     
     */
    public void setSchedule10B(Schedule10B value) {
        this.schedule10B = value;
    }

    /**
     * Gets the value of the schedule10BA property.
     * 
     * @return
     *     possible object is
     *     {@link Schedule10BA }
     *     
     */
    public Schedule10BA getSchedule10BA() {
        return schedule10BA;
    }

    /**
     * Sets the value of the schedule10BA property.
     * 
     * @param value
     *     allowed object is
     *     {@link Schedule10BA }
     *     
     */
    public void setSchedule10BA(Schedule10BA value) {
        this.schedule10BA = value;
    }

    /**
     * Gets the value of the schedule80G property.
     * 
     * @return
     *     possible object is
     *     {@link Schedule80G }
     *     
     */
    public Schedule80G getSchedule80G() {
        return schedule80G;
    }

    /**
     * Sets the value of the schedule80G property.
     * 
     * @param value
     *     allowed object is
     *     {@link Schedule80G }
     *     
     */
    public void setSchedule80G(Schedule80G value) {
        this.schedule80G = value;
    }

    /**
     * Gets the value of the schedule80IA property.
     * 
     * @return
     *     possible object is
     *     {@link Schedule80IA }
     *     
     */
    public Schedule80IA getSchedule80IA() {
        return schedule80IA;
    }

    /**
     * Sets the value of the schedule80IA property.
     * 
     * @param value
     *     allowed object is
     *     {@link Schedule80IA }
     *     
     */
    public void setSchedule80IA(Schedule80IA value) {
        this.schedule80IA = value;
    }

    /**
     * Gets the value of the schedule80IB property.
     * 
     * @return
     *     possible object is
     *     {@link Schedule80IB }
     *     
     */
    public Schedule80IB getSchedule80IB() {
        return schedule80IB;
    }

    /**
     * Sets the value of the schedule80IB property.
     * 
     * @param value
     *     allowed object is
     *     {@link Schedule80IB }
     *     
     */
    public void setSchedule80IB(Schedule80IB value) {
        this.schedule80IB = value;
    }

    /**
     * Gets the value of the schedule80IC property.
     * 
     * @return
     *     possible object is
     *     {@link Schedule80IC }
     *     
     */
    public Schedule80IC getSchedule80IC() {
        return schedule80IC;
    }

    /**
     * Sets the value of the schedule80IC property.
     * 
     * @param value
     *     allowed object is
     *     {@link Schedule80IC }
     *     
     */
    public void setSchedule80IC(Schedule80IC value) {
        this.schedule80IC = value;
    }

    /**
     * Gets the value of the scheduleVIA property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleVIA }
     *     
     */
    public ScheduleVIA getScheduleVIA() {
        return scheduleVIA;
    }

    /**
     * Sets the value of the scheduleVIA property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleVIA }
     *     
     */
    public void setScheduleVIA(ScheduleVIA value) {
        this.scheduleVIA = value;
    }

    /**
     * Gets the value of the scheduleSTTC property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleSTTC }
     *     
     */
    public ScheduleSTTC getScheduleSTTC() {
        return scheduleSTTC;
    }

    /**
     * Sets the value of the scheduleSTTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleSTTC }
     *     
     */
    public void setScheduleSTTC(ScheduleSTTC value) {
        this.scheduleSTTC = value;
    }

    /**
     * Gets the value of the scheduleSI property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleSI }
     *     
     */
    public ScheduleSI getScheduleSI() {
        return scheduleSI;
    }

    /**
     * Sets the value of the scheduleSI property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleSI }
     *     
     */
    public void setScheduleSI(ScheduleSI value) {
        this.scheduleSI = value;
    }

    /**
     * Gets the value of the scheduleEI property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleEI }
     *     
     */
    public ScheduleEI getScheduleEI() {
        return scheduleEI;
    }

    /**
     * Sets the value of the scheduleEI property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleEI }
     *     
     */
    public void setScheduleEI(ScheduleEI value) {
        this.scheduleEI = value;
    }

    /**
     * Gets the value of the scheduleMAT property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleMAT }
     *     
     */
    public ScheduleMAT getScheduleMAT() {
        return scheduleMAT;
    }

    /**
     * Sets the value of the scheduleMAT property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleMAT }
     *     
     */
    public void setScheduleMAT(ScheduleMAT value) {
        this.scheduleMAT = value;
    }

    /**
     * Gets the value of the scheduleMATC property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleMATC }
     *     
     */
    public ScheduleMATC getScheduleMATC() {
        return scheduleMATC;
    }

    /**
     * Sets the value of the scheduleMATC property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleMATC }
     *     
     */
    public void setScheduleMATC(ScheduleMATC value) {
        this.scheduleMATC = value;
    }

    /**
     * Gets the value of the scheduleDDT property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleDDT }
     *     
     */
    public ScheduleDDT getScheduleDDT() {
        return scheduleDDT;
    }

    /**
     * Sets the value of the scheduleDDT property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleDDT }
     *     
     */
    public void setScheduleDDT(ScheduleDDT value) {
        this.scheduleDDT = value;
    }

    /**
     * Gets the value of the scheduleIT property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleIT }
     *     
     */
    public ScheduleIT getScheduleIT() {
        return scheduleIT;
    }

    /**
     * Sets the value of the scheduleIT property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleIT }
     *     
     */
    public void setScheduleIT(ScheduleIT value) {
        this.scheduleIT = value;
    }

    /**
     * Gets the value of the scheduleTDS2 property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleTDS2 }
     *     
     */
    public ScheduleTDS2 getScheduleTDS2() {
        return scheduleTDS2;
    }

    /**
     * Sets the value of the scheduleTDS2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleTDS2 }
     *     
     */
    public void setScheduleTDS2(ScheduleTDS2 value) {
        this.scheduleTDS2 = value;
    }

    /**
     * Gets the value of the scheduleTCS property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleTCS }
     *     
     */
    public ScheduleTCS getScheduleTCS() {
        return scheduleTCS;
    }

    /**
     * Sets the value of the scheduleTCS property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleTCS }
     *     
     */
    public void setScheduleTCS(ScheduleTCS value) {
        this.scheduleTCS = value;
    }

    /**
     * Gets the value of the scheduleDDTP property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleDDTP }
     *     
     */
    public ScheduleDDTP getScheduleDDTP() {
        return scheduleDDTP;
    }

    /**
     * Sets the value of the scheduleDDTP property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleDDTP }
     *     
     */
    public void setScheduleDDTP(ScheduleDDTP value) {
        this.scheduleDDTP = value;
    }

    /**
     * Gets the value of the itrScheduleUD property.
     * 
     * @return
     *     possible object is
     *     {@link ITRScheduleUD }
     *     
     */
    public ITRScheduleUD getITRScheduleUD() {
        return itrScheduleUD;
    }

    /**
     * Sets the value of the itrScheduleUD property.
     * 
     * @param value
     *     allowed object is
     *     {@link ITRScheduleUD }
     *     
     */
    public void setITRScheduleUD(ITRScheduleUD value) {
        this.itrScheduleUD = value;
    }

    /**
     * Gets the value of the scheduleTR1 property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleTR1 }
     *     
     */
    public ScheduleTR1 getScheduleTR1() {
        return scheduleTR1;
    }

    /**
     * Sets the value of the scheduleTR1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleTR1 }
     *     
     */
    public void setScheduleTR1(ScheduleTR1 value) {
        this.scheduleTR1 = value;
    }

    /**
     * Gets the value of the scheduleFA property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleFA }
     *     
     */
    public ScheduleFA getScheduleFA() {
        return scheduleFA;
    }

    /**
     * Sets the value of the scheduleFA property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleFA }
     *     
     */
    public void setScheduleFA(ScheduleFA value) {
        this.scheduleFA = value;
    }

    /**
     * Gets the value of the itrScheduleFSI property.
     * 
     * @return
     *     possible object is
     *     {@link ITRScheduleFSI }
     *     
     */
    public ITRScheduleFSI getITRScheduleFSI() {
        return itrScheduleFSI;
    }

    /**
     * Sets the value of the itrScheduleFSI property.
     * 
     * @param value
     *     allowed object is
     *     {@link ITRScheduleFSI }
     *     
     */
    public void setITRScheduleFSI(ITRScheduleFSI value) {
        this.itrScheduleFSI = value;
    }

    /**
     * Gets the value of the scheduleFSI property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleFSI }
     *     
     */
    public ScheduleFSI getScheduleFSI() {
        return scheduleFSI;
    }

    /**
     * Sets the value of the scheduleFSI property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleFSI }
     *     
     */
    public void setScheduleFSI(ScheduleFSI value) {
        this.scheduleFSI = value;
    }

}
