//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.05 at 01:02:46 AM PDT 
//


package in.gov.incometaxindiaefiling.y2013_2014;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/master}ScheduleFSI" maxOccurs="unbounded"/>
 *         &lt;element name="TotalIncomeOutIndia">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TotalIncomeOutIndiaDTAA">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TotalIncomeOutIndiaWoDTAA">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong">
 *               &lt;totalDigits value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "scheduleFSI",
    "totalIncomeOutIndia",
    "totalIncomeOutIndiaDTAA",
    "totalIncomeOutIndiaWoDTAA"
})
@XmlRootElement(name = "ITRScheduleFSI")
public class ITRScheduleFSI {

    @XmlElement(name = "ScheduleFSI", required = true)
    protected List<ScheduleFSI> scheduleFSI;
    @XmlElement(name = "TotalIncomeOutIndia", required = true, defaultValue = "0")
    protected BigInteger totalIncomeOutIndia;
    @XmlElement(name = "TotalIncomeOutIndiaDTAA", required = true, defaultValue = "0")
    protected BigInteger totalIncomeOutIndiaDTAA;
    @XmlElement(name = "TotalIncomeOutIndiaWoDTAA", required = true, defaultValue = "0")
    protected BigInteger totalIncomeOutIndiaWoDTAA;

    /**
     * Gets the value of the scheduleFSI property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scheduleFSI property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScheduleFSI().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScheduleFSI }
     * 
     * 
     */
    public List<ScheduleFSI> getScheduleFSI() {
        if (scheduleFSI == null) {
            scheduleFSI = new ArrayList<ScheduleFSI>();
        }
        return this.scheduleFSI;
    }

    /**
     * Gets the value of the totalIncomeOutIndia property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalIncomeOutIndia() {
        return totalIncomeOutIndia;
    }

    /**
     * Sets the value of the totalIncomeOutIndia property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalIncomeOutIndia(BigInteger value) {
        this.totalIncomeOutIndia = value;
    }

    /**
     * Gets the value of the totalIncomeOutIndiaDTAA property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalIncomeOutIndiaDTAA() {
        return totalIncomeOutIndiaDTAA;
    }

    /**
     * Sets the value of the totalIncomeOutIndiaDTAA property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalIncomeOutIndiaDTAA(BigInteger value) {
        this.totalIncomeOutIndiaDTAA = value;
    }

    /**
     * Gets the value of the totalIncomeOutIndiaWoDTAA property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalIncomeOutIndiaWoDTAA() {
        return totalIncomeOutIndiaWoDTAA;
    }

    /**
     * Sets the value of the totalIncomeOutIndiaWoDTAA property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalIncomeOutIndiaWoDTAA(BigInteger value) {
        this.totalIncomeOutIndiaWoDTAA = value;
    }

}
